# Generated by Django 2.2.5 on 2019-09-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_new', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot_img',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
