# Generated by Django 2.2.5 on 2019-09-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_new', '0002_auto_20190908_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot_img',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plot_img'),
        ),
    ]
